---
version: '3'

services:
  api:
    container_name: api
    image: aem_adaptor:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    #volumes:
    #  - ./:/app
    #environment:
    #  FASTAPI_PORT: 8080
    depends_on:
      - "redis"
  redis:
    container_name: redis
    image: redis:7-bullseye
    ports:
      - "6379:6379"
    expose:
      - 6379
