---
version: '3'

services:
  api:
    container_name: api
    image: aem_adaptor:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    #volumes:
    #  - ./:/app
    #environment:
    #  FASTAPI_PORT: 8080
    depends_on:
      - "redis"
  redis:
    container_name: redis
    build: 
      context: .
      args:
        REDIS_USER: redis_user
        REDIS_PASSWORD: vKJFYqEuXAr9pE5crojtQsUpausnKpAf
        REDIS_USER_PERMISSIONS: +@all allkeys allchannels
        DEFAULT_USER: default
        DEFAULT_PASSWORD: LhoMSE3UkrfE7rs7NuufQebj3CaTaJ4i
        DEFAULT_USER_PERMISSIONS: +@all allkeys allchannels
      dockerfile: Dockerfile.redisdev
    image: redisdev:latest
    ports:
      - "6379:6379"
    expose:
      - 6379